import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // className={inter.className}
  return (
    <html lang="en">
      <body className="flex ">
        <div className="basis-[43%] w-full max-h-screen">
          <img src="/main.jpg" className="w-full" />
          {/* <img src="/large.png" alt="" />
          <img src="/group1.png" alt="" /> */}
          {/* <div className="flex flex-col items-center">
            <img src="/group1.png" alt="" className="w-full" />
            <img src="/group2.png" alt="" className="w-full" />
            <img src="/group3.png" alt="" className="w-full" />
            <img src="/group4.png" alt="" className="w-full" />
            <img src="/group5.png" alt="" className="w-full" />
            <img src="/group6.png" alt="" className="w-full" />
          </div> */}
        </div>
        <div className="flex-1">{children}</div>
      </body>
    </html>
  );
}
